apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comfort-by-default
spec:
  project: default
  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.14.0
    helm:
      values: |
        minecraftServer:
          eula: true
          version: "1.20.4"
          type: "PAPER"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
