apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comfort-by-default
spec:
  project: default
  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.14.0
    helm:
      release-name: comfort-by-default
      values: |
        env:
          EULA: true
          TYPE: "PAPER"
  destination:
    server: "https://kubernetes.default.svc"
