apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-2
  labels:
    name: nginx-test-2
spec:
  containers:
    - name: nginx-test-2
      image: nginx:1.17.2
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 80
